fix README
Sotq17/chat-space pull request #2
Opened 2019-03-16 10:39 UTC by Sotq17

# WHAT
READMEを編集

# WHY
データベース設計のため
*間違えてmasterにpushしてしまっていたので、訂正して再度提出します。
  ご確認の程お願いします。

2019-03-16 11:24 UTC, yuki-uchida requested changes

2019-03-16 11:24 UTC, yuki-uchida commented on README.md
> +|user_id|integer|null: false|
外部キーの場合にはrefference型としましょう

2019-03-16 11:24 UTC, yuki-uchida commented on README.md
> +|group_name|string|null: false|
nameで良いです

2019-03-16 12:18 UTC, Sotq17 commented on README.md
> +|user_id|integer|null: false|
ご確認ありがとうございます！
下記の通り修正しました

|user_id|refernces|foreign_key:true|
|group_id|refernces|foreign_key:true|

2019-03-16 12:18 UTC, Sotq17 commented on README.md
> +|group_name|string|null: false|
group_nameをnameに修正しました

2019-03-18 18:23 UTC, ghost requested changes

2019-03-18 18:23 UTC, hiroki5123 commented on README.md
> +|group_id|integer|null: false|
こちらは必要ありません

2019-03-18 18:23 UTC, hiroki5123 commented on README.md
> +
中韓テーブルもhas_manyしましょう

2019-03-18 18:23 UTC, hiroki5123 commented on README.md
> +- has_many :users ,through: :users_groups
こちらも

2019-03-19 04:01 UTC, Sotq17 commented on README.md
> +|group_id|integer|null: false|
ご確認ありがとうございます！

group_id|integer|null: falseを削除します。

2019-03-19 04:01 UTC, Sotq17 commented on README.md
> +
has_many :users_groupsを追加します

2019-03-19 04:01 UTC, Sotq17 commented on README.md
> +- has_many :users ,through: :users_groups
has_many :users_groupsを追加します

2019-03-19 04:59 UTC, hirozak commented on README.md
> +|name|string|
indexつけましょう

2019-03-19 04:59 UTC, hirozak commented on README.md
> +>>>>>>> Stashed changes
コンフリクト解消の残り消しましょう

2019-03-19 05:04 UTC, Sotq17 commented on README.md
> +|name|string|
御確認ありがとうございます！

|name|string|index: true|　と変更しました

2019-03-19 05:04 UTC, Sotq17 commented on README.md
> +>>>>>>> Stashed changes
コンフリクト解消の残り部分を削除しました

2019-03-19 05:14 UTC, miyagit reviewed
変更差分が殆ど無いのですべてのreadmeが載っているPRを挙げましょう。

2019-03-19 06:16 UTC, hirozak commented
コンフリクト直しましょう

2019-03-19 07:42 UTC, TOMARUMARU commented on README.md
> +|name|string|index: true|
uniqueとindexをつけましょう

2019-03-19 07:42 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|index: true, null: false|
こちらは不要です

2019-03-19 07:42 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|
外部キーをつけましょう

2019-03-19 07:42 UTC, TOMARUMARU commented on README.md
> +|group_id|integer|
外部キーをつけましょう

2019-03-19 07:57 UTC, Sotq17 commented on README.md
> +|group_id|integer|
外部キーの記述を追記します

2019-03-19 07:58 UTC, Sotq17 commented on README.md
> +|name|string|index: true|
ご確認いただきありがとうございます
uniqueを追加でつけました

2019-03-19 07:58 UTC, Sotq17 commented on README.md
> +|user_id|integer|index: true, null: false|
かしこまりました。削除します。

2019-03-19 07:58 UTC, Sotq17 commented on README.md
> +|user_id|integer|
外部キーの記述を追記します

2019-03-19 08:45 UTC, TOMARUMARU approved these changes
LGTMです。お疲れ様でした

2019-03-19 08:45 UTC, Sotq17 commented
ありがとうございます！

2019-03-19 08:46 UTC, merged